### ISSUE TITLE
Copy Attribute Array, Attribute Matrix, Data Container Filters

### ISSUE THREAD

**Issue by tuks188** [BlueQuartzSoftware/DREAM3D#182]
In thinking about all the filters where one would potentially want a "create new data container" option, as in the crop filter, we figured it would be better to write copy filters for every level of data which will be housed in SIMPL.

**Comment by wlenthe** [comment]
The copy data container functionality sometime causes an error when writing the resulting data container (Write DREAM.3D Data File: Error writing DataContainer AtributeMatricies -803). Github doesn't allow attaching non-images files but the pipeline to reproduce this issue is:
1. read data file
2. segment features
3. find feature sizes
4. minimum size
5. copy data container
6. write data file
