### ISSUE TITLE
"Find GBPD (metric-based approach)" causes segmentation fault

### ISSUE THREAD

**Issue by Yufeng-shen** [BlueQuartzSoftware/DREAM3D#600]
Hi all,
When I using Dream.3d (v6.3.29), the "Find GBPD (metric-based approach)" filter causes segmentation fault. Just use the sample data SmallIN100 and follow the prebuilt pipeline and add a "Generate Triangle Face Ids" filter can reproduce this bug.

Thanks!
Yufeng

**Comment by kglowins** [comment]
Indeed, there's an issue in the latest DREAM.3D release. It can be easily reproduced using SmallIN100 data and the prebuilt pieplines: full reconstruction -> quick mesh -> smooth, and then run 'Find GBPD...'. Have you run some basic regression tests before releasing the latest version of DREAM.3D? I'm guessing that the bug might have been introduced recently as something in DREAM.3D core has changed. Let me know if I'm wrong.

Krzysztof

**Comment by imikejackson** [comment]
We run some basic checks on the release but the amount of unit tests is known to be woefully inadequate for the project. I will try to check into this before the next release.

**Comment by sdonegan** [comment]
This issue appears to be caused by a name conflict in the symbol table for the SurfaceMeshing plugin.  Specifically, both the FindGBPDMetricBased and FindGBCDMetricBased filters have helper classes named "TrisSelector" and "ProbeDistrib".  These were defined outside of any scope.  When the FindGBPD filter instantiated an instance of the TrisSelector class, it ended up creating the version implemented in the FindGBCD filter since it was the first available, which had different sized arrays leading to an out-of-bounds error.

I'm not sure why this wasn't caught before (maybe just a Windows issue?), but I have fixed the issue by placing the various helper classes in both classes in namespaces to properly scope them; both filters appear to be working correctly without crashes when running on the small IN100 data set.  I'll submit a pull request for the changes, and once those changes are pulled in the nightly builds of DREAM.3D should start functioning once again.

**Comment by kglowins** [comment]
Interesting. Thank you for fixing this!
