### ISSUE TITLE
GenerateIPF Colors filter does not validate phase data and will cause unexpected results or crashes.

### ISSUE THREAD

**Issue by imikejackson** [BlueQuartzSoftware/DREAM3D#718]
User reported issues reading CTF files. The CTF in question only declared 1 phase in the header but the phase column had values of 2 for the indexed points. When using the GenerateIPFColors filter the actual code did not validate that the phase values were less than the number of phases in the ensemble attribute matrix. When testing on macOS we would effectively walk off the end of the crystal structures array and get a random crystal structure which is used to generate the IPF Color. If tested on Windows this _should_ cause a crash.

**Comment by AmitS07** [comment]
Hi All, 
I am having similar issue. My raw EBSD data is in .ctf file. I just want to correct its reference basis actors. To do so, I am using following the Pipeline (shared below)
[Pipeline_reference_correction.json](https://github.com/user-attachments/files/16619491/Pipeline_reference_correction.json)

It does change the basis vectors. But, unfortunately, the unindexed-points change to indexed points i.e. phase of unindexed pixels changed from "0" to "1". All unindexed pixels' orientations became "red" instead of "black". This might be due to fact that I am not able to use the "Mask_error"  (a Mask based on "Error" matric of ctf data with threshold of Error=0). 

Please let me know how to and which filter should be used to ensure unindexed-pixel's phase remains the "0" and should not convert to "1"

**Comment by imikejackson** [comment]
This is not the same problem. As was commented on in the other bug that you have filed.
