### ISSUE TITLE
Problem with surface normals

### ISSUE THREAD

**Issue by eugenianietov** [BlueQuartzSoftware/DREAM3D#999]
Hi everyone,

I am working with a 3D volume of a sample and I am creating a surface mesh with Dream3D. The problem is that I am still getting abnormal triangle winding within grain boundaries as shown in the images below. However, the FaceLabels are consistent within the faces (they don't change within the same face). Any idea of what might be wrong?

![test_FaceLabels_Y_W](https://user-images.githubusercontent.com/26228093/177941364-80febf84-0bdf-4d3f-9a0e-7e8e6f3adc02.png)
![test_Normals_Y_W](https://user-images.githubusercontent.com/26228093/177941372-a42ecdbf-dcf1-42b1-b88e-f1326bb98fe1.png)

I also provide my pipeline in case you want to take a look. Thanks a lot in advance!!

[2-Ti_SurfaceMesh.json.zip](https://github.com/BlueQuartzSoftware/DREAM3D/files/9069922/2-Ti_SurfaceMesh.json.zip)

Eugenia

**Comment by imikejackson** [comment]
This is by design. DREAM3D only stores a single triangle instead of a pair of triangles in order to keep memory usage low (and the complexity of the algorithms reasonable). So anything beyond a bare minimal microstructure it is impossible to have consistent normals among all faces of all grains. If I you could describe what you want to do with the microstructure model we might be able to provide some ideas on how to get from A to B.

**Comment by eugenianietov** [comment]
Hi Mike!

Thanks for your answer. I finally fixed it post-processing the surface mesh with Python. I simply flipped the normals pointing towards the grain's centroid; not a big deal. I just wanted to know if was doing something wrong since the triangle winding was fixed in a prior Dream3D release. Thanks anyway!

Eugenia
